### ISSUE TITLE
We need a template for guides

### ISSUE THREAD

**Issue by asclines** [CodeSpaceHQ/AppliedAlgorithms#26]
Like the title says, we need a template for the guides. 
Similar to what we did for the coding problems. See #2 
Any thoughts?

The running template I have now is:

# [PROBLEM-TYPE] Guide

## Additional Resources

**Comment by NilsG-S** [comment]
Should we have a section that would have information on how to start solving problems of this type? Or would that be handled in the Overview section?

Something like:

## Overview

## How to Start

**Comment by isaac-gs** [comment]
I wouldn't worry about that. We should keep this simple to begin with and only add stuff as needed

**Comment by asclines** [comment]
Yeah, the "How to Start" part should be implicitly handled in the problem guides.

What about a section that briefly discusses common data structures used in these types of problems?

**Comment by NilsG-S** [comment]
Discussing data structures could be helpful; potentially helping people frame the solution of the problem properly. The only real downside would be that adding data structures increases the complexity of the guides.

**Comment by asclines** [comment]
Well, @NilsG-S I wouldnt say go into detail on them so much as merely list them for the reader to further their knowledge.

**Comment by asclines** [comment]
I believe this has been figured out.
