### ISSUE TITLE
Greedy Guide

### ISSUE THREAD

**Issue by asclines** [CodeSpaceHQ/AppliedAlgorithms#29]
This guide should introduce the readers to how to solve a Greedy-style problem.
The assumptions that should be made here is that the reader is familiar with at least one programming language but apart from that, very little should be assumed.

The guide should be provide a brief overview of the type of problems under the Greedy label and cover enough information to get the user started.

The guide should provide resources for continued education whether to enhance what the guide is saying or to continue into advanced topics under this type of problem.

**Comment by isaac-gs** [comment]
Forgot to close with PR
