### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by asclines** [CodeSpaceHQ/AppliedAlgorithms#9]
[Problem Link](https://www.hackerrank.com/challenges/contacts)

**Comment by asclines** [comment]
Since this problem is actually under a **Data Structures** and not **Algorithms**, should we add a layer to the file hierarchy to the `Guide` folder that splits into  **Data Structures, Algorithms** etc.. ?
@ASAAR

**Comment by ghost** [comment]
I'm ok with this, maybe instead of "Algorithms" we have sub folders for the type of data structure the problem deals with as in "Trie" or "Heap" as the sub directories?

**Comment by asclines** [comment]
But what about problems that involve multiple data structures?

**Comment by isaac-gs** [comment]
@asclines what if we just included tags in our problem descriptions that allow a user to search for that tag (using GitHub or bash) and find problems with that tag? Tags would be useful for data structure labels

**Comment by asclines** [comment]
@ASAAR That was my initial idea with the tags. That being said, I think the problem we are trying to solve here is not what data structures are in a problem, but where to put the problems that are under the data structures sections of hackerrank as opposed to the algorithms section.

**Comment by isaac-gs** [comment]
@asclines yeah, I guess my idea there was that we could just ignore the problem by telling people "if you want to know how to use X data structure, search for one of Y tags"

**Comment by asclines** [comment]
@ASAAR what do you mean ignore it? Where would you place this problem then?

**Comment by isaac-gs** [comment]
Sorry. Basically you know the way that we categorize issues in the project? We could provide a list of tags that people can search for which direct them to different problems or code. So we could make tags that direct you to data structures or even python/java/cpp.

We could also just include a simple wiki page with a link to every problem that falls in a data structure category..

Of course, you could also make the argument that it makes more sense to organize this repo based on data structures rather than algorithms. So...

**Comment by asclines** [comment]
@ASAAR I mean the problem that this issue is talking about. [This problem](https://www.hackerrank.com/challenges/contacts). Please go to that problem and see how HackerRank categorizes this problem. 
I'm not talking about tags, categories etc, I'm talking about where to put problems that are categorized as data structures instead of algorithms.. 

I'm also not talking about restructuring this project, I'm talking about extending it beyond algorithms so we can include more types of problems that fall under different [HackerRank Domains](https://www.hackerrank.com/challenges/contacts)

**Comment by isaac-gs** [comment]
Right, but that I think is where our fundamental misunderstanding is coming from. Plenty of algorithms exist which use one data structure (DS) or another. Unless you mean creating a sub-directory for DS specific problems, in which case that's fine, but it doesn't help organize solutions by DS
